# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    must_be_immutable: ignore

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    prefer_const_constructors: true
    prefer_final_fields: false
    prefer_foreach: false
    avoid_function_literals_in_foreach_calls: false
    overridden_fields: false
    annotate_overrides: false
    unnecessary_overrides: false
    use_full_hex_values_for_flutter_colors: false
    avoid_print: false
    unnecessary_new: false
    prefer_initializing_formals: false
    prefer_collection_literals: false
    depend_on_referenced_packages: false
    no_leading_underscores_for_local_identifiers: false
    use_build_context_synchronously: false
    sort_child_properties_last: false
    curly_braces_in_flow_control_structures: false
    prefer_single_quotes: false
    void_checks: false
    use_key_in_widget_constructors: false
    slash_for_doc_comments: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
