name: sia_host_mobile
description: Mobile to easily manage your Sia host.
version: 1.0.0+10
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.1
  auto_route: ^10.0.1
  better_player_plus: ^1.0.8
  bloc: ^9.0.0
  bottom_navy_bar: ^6.1.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  disk_space_plus:
    git:
      url: https://github.com/Tooltopia/disk_space_forked
      ref: a41cc2f
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^10.1.2
  fl_chart: ^0.71.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.19.0
  just_audio: ^0.10.2
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  mime: ^2.0.0
  open_filex: ^4.7.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  renterd:
    # git:
    # url: https://github.com/DartSiaProject/dartsia.git
    # ref: main
    # path: packages/renterd
    path: ../../../../packages/dartsia/packages/renterd
  share_plus: ^11.0.0
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_pdfviewer: ^29.1.41
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/file_exts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
