name: sia_host_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  bottom_navy_bar: ^6.1.0
  cached_network_image: ^3.4.1
  chewie: ^1.11.3
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^10.1.2
  fl_chart: ^0.71.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  internet_connection_checker_plus: ^2.7.1
  intl: ^0.19.0
  just_audio: ^0.10.1
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  renterd:
    # git:
    # url: https://github.com/DartSiaProject/dartsia.git
    # ref: main
    # path: packages/renterd
#    path: ../../../../packages/dartsia/packages/renterd/
    path: ../../packages/dartsia/packages/renterd
  smooth_page_indicator: ^1.2.1
  video_player: ^2.9.5

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/Manrope/